name: Autograding Tests
'on':
- workflow_dispatch
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: install dependencies
      id: install-dependencies
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: install dependencies
        setup-command: ''
        command: sudo -H pip3 install -r requirements.txt
        timeout: 10
    - name: grading
      id: grading
      uses: classroom-resources/autograding-python-grader@v1
      with:
        timeout: 10
        max-score: 25
        setup-command: sudo -H pip3 install pytest
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        INSTALL-DEPENDENCIES_RESULTS: "${{steps.install-dependencies.outputs.result}}"
        GRADING_RESULTS: "${{steps.grading.outputs.result}}"
      with:
        runners: install-dependencies,grading
